sonar.organization=mcc-mak
sonar.projectKey=mcc-mak_security-certs
sonar.projectName=security-certs

sonar.sources=codebase
sonar.exclusions=**/*.pdf,**/*.svg,**/*.html,**/*.csv,**/.git/**,.scannerwork/**
sonar.coverage.exclusions=**

sonar.sourceEncoding=UTF-8
